# 지난 시간 문제 풀이

In [ ]:
# 구구단 1단 ~ 9단 중 홀수만 모두 출력하기

1 X 1 =  1  1 X 3 =  3  1 X 5 =  5  1 X 7 =  7  1 X 9 =  9

3 X 1 =  3  3 X 3 =  9  3 X 5 = 15  3 X 7 = 21  3 X 9 = 27

5 X 1 =  5  5 X 3 = 15  5 X 5 = 25  5 X 7 = 35  5 X 9 = 45

7 X 1 =  7  7 X 3 = 21  7 X 5 = 35  7 X 7 = 49  7 X 9 = 63

9 X 1 =  9  9 X 3 = 27  9 X 5 = 45  9 X 7 = 63  9 X 9 = 81

In [ ]:
# 구구단 1단 ~ 9단 중 짝수만 모두 출력하기

1 X 2 =  2  1 X 4 =  4  1 X 6 =  6  1 X 8 =  8
2 X 1 =  2  2 X 2 =  4  2 X 3 =  6  2 X 4 =  8  2 X 5 = 10  2 X 6 = 12  2 X 7 = 14  2 X 8 = 16  2 X 9 = 18
3 X 2 =  6  3 X 4 = 12  3 X 6 = 18  3 X 8 = 24
4 X 1 =  4  4 X 2 =  8  4 X 3 = 12  4 X 4 = 16  4 X 5 = 20  4 X 6 = 24  4 X 7 = 28  4 X 8 = 32  4 X 9 = 36
5 X 2 = 10  5 X 4 = 20  5 X 6 = 30  5 X 8 = 40
6 X 1 =  6  6 X 2 = 12  6 X 3 = 18  6 X 4 = 24  6 X 5 = 30  6 X 6 = 36  6 X 7 = 42  6 X 8 = 48  6 X 9 = 54
7 X 2 = 14  7 X 4 = 28  7 X 6 = 42  7 X 8 = 56
8 X 1 =  8  8 X 2 = 16  8 X 3 = 24  8 X 4 = 32  8 X 5 = 40  8 X 6 = 48  8 X 7 = 56  8 X 8 = 64  8 X 9 = 72
9 X 2 = 18  9 X 4 = 36  9 X 6 = 54  9 X 8 = 72

## list를 활용한 반복문

In [ ]:
# list에 있는 모든 숫자의 제곱을 구하고, 새로운 리스트에 저장하기
# 예시 list입니다. 수정하지 마세요!
numbers = [i for i in range(1, 21)]

# 결과를 담을 리스트 result 선언하기
result = []

# for문 활용해서 numbers 의 원소를 num이라는 임시 변수로 부르고,
# 제곱한 값을 result에 삽입하기


# result 출력하기
print(result)

numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
result: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

In [ ]:
# 1부터 50까지의 숫자 중에서 짝수만 모은 리스트 result를 만들고 출력하기

result = []

# for문 활용해서 임시 변수 i를 1부터 50까지 돌린다.(range() 함수 활용)
# if 문을 활룔하여 짝수면 result에 삽입하기


# result 출력하기
print(result)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

In [ ]:
# str_list의 원소인 문자열들의 길이를 각각 출력하기
str_list = ["approach", "declaring", "initialized", "variable", "structure"]

# for문 활용하여 str_list의 원소를 word라는 임시변수로 돌린다.
# word의 길이를 출력한다.

approach의 길이는 8
declaring의 길이는 9
initialized의 길이는 11
variable의 길이는 8
structure의 길이는 9

### dictionary를 활용한 반복문

#### 다음 과일 정보가 입력된 fruits 변수를 활용해 아래 문제를 해결하세요.

In [ ]:
# 이 데이터는 실행만 하고 수정 금지
fruits = {
    "사과": 3000,
    "바나나": 2000,
    "체리": 2500,
    "배": 4000,
    "감": 1500,
    "오렌지": 1000,
    "석류": 3500,
    "포도": 3300,
}

#### 1. fruits에 담긴 과일들의 이름을 출력해보세요.

In [ ]:
# for문, 딕셔너리 method 이용하기

사과
바나나
체리
배
감
오렌지
석류
포도

#### 2. fruits에 담긴 과일들의 이름과 가격을 출력해보세요.

In [ ]:
# for문, Unpacking, 딕셔너리 method 이용하기
# ex) 사과: 3000원

사과: 3000원
바나나: 2000원
체리: 2500원
배: 4000원
감: 1500원
오렌지: 1000원
석류: 3500원
포도: 3300원

#### 3. 가장 비싼 과일과, 가장 싼 과일의 이름과 가격을 각각 출력하세요.

- 비싼 과일: 배 4000원
- 싼 과일: 오렌지 1000원

In [ ]:
# 가장 비싼 과일의 데이터를 저장할 expensive 라는 dictionary형식의 변수 지정
# key로 "name"과 "price"를 만들고 적당한 값으로 초기화


# 가장 싼 과일의 데이터를 저장할 cheap라는 dictionary형식의 변수 지정
# key로 "name"과 "price"를 만들고 적당한 값으로 초기화


# for 문을 활용하여 fruits의 name과 price를 위에 만든 dictionary와 비교한다.
# if 문 활용하기


# 가장 비싼 과일과 싼 과일의 정보를 출력한다.

비싼 과일: 배 4000
싼 과일: 오렌지 1000

#### 단어 빈도수 계산하기

In [ ]:
# 다음 문장에서 각 단어가 몇 번씩 등장하는지 dictionary를 만들어 저장하고, 출력하기
# 단어의 등장 횟수를 저장할 dictionary 변수 frequency 선언
sentence = "apple banana apple strawberry banana lemon apple lemon"
frequency = {}

# 문자열 데이터는 문자열.split() 메서드를 이용하면
# 띄어쓰기 단위로 잘라 리스트로 만들어 준다
# 문자열을 잘라 str_list 변수로 저장한다.


# for 문 활용, str_list의 원소를 임시변수 word로 돌린다.
# frequency에 이미 해당 단어가 있다면 빈도를 1 더해주고,
# 없다면 만들어준다.


# frequency 의 값을 key와 value의 쌍으로 출력한다.

apple: 3회
banana: 2회
strawberry: 1회
lemon: 2회

# 예외 처리

> try와 except 사용

- TypeError: 잘못된 자료형을 연산이나 함수에 적용할 때

- IndexError: 리스트의 범위를 벗어난 잘못된 인덱싱

- NameError: 변수의 이름을 찾을 수 없을 때

- ValueError: 연산이나 내장 함수에서 인수가 적절치않은 값을 가지고 있을 때

- ZeroDivisionError: 0으로 나눌 때

In [ ]:
# IndexError

arr = [0, 1, 2, 3, 4]

# arr의 5번째 원소를 출력하기

In [ ]:
# ZeroDivisionError

x = 10
y = 0
z = x / y

## 예외 무시하기

In [ ]:
# 사람 이름을 입력받아 변수 name에 할당


# name 변수의 값을 정수로 변환해 num 변수에 할당


# 예외 처리

# 함수

## 함수 정의

def 함수이름(매개변수): 매개변수 = parameter

> return 반환값

함수이름(전달인자) 전달인자 = argument

In [1]:
# 함수 hello 선언


# 함수가 선언되면 "hello"를 출력


# 함수 hello 호출

## 인자(argument) 전달

In [ ]:
#  함수 twice 선언 (parameter로 정수형 number)


# number의 2배를 리턴


n = int(input("정수: "))

print(twice(n))

## 무작위값 사용하기

In [ ]:
import random  # 무작위 값을 만들 때 쓰는 모듈

# 함수 random_function 선언 (parameter로 정수형 low, high)


# 무작위 값을 리턴


low = int(input("최소값: "))
high = int(input("최대값: "))

# 함수 random_function 호출하고 출력하기(argument로 low, high 전달)

## Scope

전역(global)변수와 지역(local)변수 구분하기

In [ ]:
a = 100

# 함수 print_a 선언


# a의 값 출력하기


# 함수 print_a 호출

In [ ]:
a = 100

# 함수 print_a 선언


    a = 1
    # a의 값 출력하기


# 함수 print_a 호출


# a의 값 출력하기

In [7]:
a = 100

# 함수 print_a 선언


    # 변수 a를 global 선언(전역변수를 직접 사용하겠다는 뜻)
    # 이 방법은 사용을 권장하지 않음
    global a
    a = 1
    # a의 값 출력하기


# 함수 print_a 호출


# a의 값 출력하기

In [ ]:
# 함수 input_nickname 선언


# 문자열 자료를 입력받아 nickname 변수에 할당


# name 출력
print(nickname)

In [ ]:
name = "홍길동"
age = 20
phone_number = "010-1111-2222"

print(f"함수 호출 전\nname: {name}, age: {age}, phone_number: {phone_number}\n========================\n")

# 함수 input_personal 선언(parameter로 문자열 name, 정수 age, 문자열 phone_number)


    print(f"함수 시작\nname: {name}, age: {age}, phone_number: {phone_number}\n========================\n")

    # 이름을 입력받아 name 변수에 할당


    # 나이를 입력받아 age 변수에 할당


    # 전화번호를 입력받아 phone_number 변수에 할당


    print(f"함수 종료\nname: {name}, age: {age}, phone_number: {phone_number}\n========================\n")

# input_personal 함수 호출 (argument로 name, age, phone_number 전달)


print(f"함수 호출 후\nname: {name}, age: {age}, phone_number: {phone_number}\n========================\n")

## Default Parameter Value

> parameter의 값이 입력되지 않을 때 자동으로 적용되는 값

In [ ]:
# parameter에 default value 선언 X
def personal_info(name, age):
    return f"이름은 {name}, 나이는 {age}살입니다."


name = input("이름: ")
age = int(input("나이: "))
print(personal_info(name, age))

In [ ]:
# parameter 중 뒤에 있는 age만 default value 선언
def personal_info2(name, age=0):
    return f"이름은 {name}, 나이는 {age}살입니다."


name = input("이름: ")
age = int(input("나이: "))
print(personal_info2(name, age))

In [ ]:
# parameter 중 앞에 있는 name만 default value 선언
# Error 발생!!!!!!!!
def personal_info3(name="홍길동", age):
    return f"이름은 {name}, 나이는 {age}살입니다."

name = input("이름: ")
age = int(input("나이: "))
print(personal_info3(name, age))

## 재귀함수 (Recursive Function)

> 자기 자신을 호출하는 함수.  
> 잘못 사용하면 컴퓨터나 서버가 다운될 수 있다.

In [ ]:
# 함수 hello 선언


# "hello world"를 출력


# 함수 hello 호출


# 함수 hello 호출

In [ ]:
# 함수 hello 선언 (parameter로 정수형 cnt)


# cnt가 0이라면 아무 값 없이 return


# f"hello world - {cnt}"를 출력


# 함수 hello 선언 (argument로 cnt-1 전달)

n = int(input("숫자: "))
hello(n)

In [ ]:
# 팩토리얼 계산하기

# 함수 factorial 선언하기 (parameter로 정수형 n)


# n이 1이라면 1을 리턴


# n * factorial(n-1) 을 리턴

n = int(input("숫자: "))
print(factorial(n))

# 퀴즈

In [3]:
# 사칙연산을 하는 함수 만들기

# 함수 calc 선언하기 (parameter로 정수형 x, y)


# x와 y를 합한 값을 plus 변수에 할당


# x에서 y를 뺀 값을 minus 변수에 할당


# x와 y를 곱한 값을 multiply 변수에 할당


# x에서 y를 나눈 값을 devide 변수에 할당
# 계산할 수 없을 때는 계산 불가라고 할당(try 사용)

# plus, minus, multiply, devide를 리턴


x = int(input())
y = int(input())
result = calc(x, y)

print(f"합: {result[0]}, 차: {result[1]}, 곱: {result[2]}, 분: {result[3]}")

x: 47
y: 13
합: 60, 차: 34, 곱: 611, 분: 3.62

In [5]:
# 가장 낮은 점수, 높은 점수, 평균점수 계산하는 함수 만들기

# 함수 score_func 선언 (parameter로 list형 scores)


# 가장 낮은 점수를 min_score 변수에 할당


# 가장 높은 점수를 max_score 변수에 할당


# 평균 점수를 avg_score 변수에 할당


# 세 변수를 리턴하기


subs = ["국어", "영어", "수학", "과학", "사회"]  # 과목 이름들
scores = [int(input(f"{sub}: ")) for sub in subs]  # 과목별 점수 입력

# 함수 score_func 호출하고 결과값을 min_score, max_score, avg_score에 할당. (argument로 scores 전달)


print(f"최저점: {min_score}\n최고점: {max_score}\n평균 점수: {avg_score}")

국어: 70
영어: 80
수학: 30
과학: 65
사회: 90
최저점: 30
최고점: 90
평균 점수: 67.0

### Dynamic Programing

> 값을 저장하는 변수를 선언해 재귀함수의 실행 속도를 압도적으로 올릴 수 있다.

In [20]:
# 피보나치 수열(시간 비교)
import time
import sys

sys.setrecursionlimit(10000)

# 함수 fibo 선언하기 (parameter로 정수형 n)


# n이 1 또는 2라면 1을 리턴


# fibo(n-1) + fibo(n-2) 을 리턴


n = 40
start_time = time.time()  # 시작 시간 체크
print(f"fibo({n})의 값: {fibo(n)}")
print(f"{time.time() - start_time}초 소요")  # 종료 시 시간에서 시작 시간을 빼서 작동 시간 체크

fibo(40)의 값: 102334155
34.59030103683472초 소요

In [21]:
# 피보나치 수열(시간 비교)
import time
import sys

sys.setrecursionlimit(10000)

# 함수 fibo 선언하기 (parameter로 정수형 n)


# n이 1 또는 2라면 1을 리턴


# d의 key값에 n이 있다면 value값 리턴


# fibo(n-1) + fibo(n-2)를 딕셔너리 d에 등록하고 리턴하기


# fibo 함수의 결과값을 저장할 빈 dictionary 자료형 d 변수 선언


n = 40
start_time = time.time()  # 시작 시간 체크
print(f"fibo({n})의 값: {fibo(n)}")
print(f"{time.time() - start_time}초 소요")  # 종료 시 시간에서 시작 시간을 빼서 작동 시간 체크

fibo(40)의 값: 102334155
0.0002338886260986328초 소요